<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>ReadyUp.Metadata</AssemblyName>
    <RootNamespace>ReadyUp.Metadata</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReadyUp.Core\ReadyUp.Core.csproj" />
  </ItemGroup>

</Project>
