<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>ReadyUp.Scanning</AssemblyName>
    <RootNamespace>ReadyUp.Scanning</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReadyUp.Core\ReadyUp.Core.csproj" />
  </ItemGroup>

</Project>
